name = "nodejs-worker-api"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

browser = { binding = "MYBROWSER", type = "browser" }

# Production environment
[vars]
ENVIRONMENT = "production"
# Specify the URL where the Worker is applied
routes = [
  { pattern = "https://nodejs-worker-api-demo.cloudexp.nl/*", script = "nodejs-worker-api" , custom_domain = true}
]

# Development environment
[env.development]
name = "nodejs-worker-api-dev"
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "nodejs-worker-api-staging"
vars = { ENVIRONMENT = "staging" }

# Configure minimal duration for cron triggers
[triggers]
crons = []

[observability.logs]
enabled = true

[kv_namespaces]
binding = "MY_KV"
id = ""  # 留空，Cloudflare会自动生成
